ARDUINO_DIR  = /usr/share/arduino

TARGET = 7segclock

BOARD_TAG    = mega2560
ARDUINO_PORT = /dev/ttyACM0  # change this to the port used by your board

ARDUINO_LIBS = Wire 
ARDUINO_LIBS += DS3231 

ARDUINO_DIR  = /usr/share/arduino
AVR_TOOLS_PATH = /usr/bin

include /usr/share/arduino/Arduino.mk
